// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Y3zjqh3wSfUNvx_vjECrdc9Lah2BwUU',
    appId: '1:364938733915:web:03ab82b668a80c4c7f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    authDomain: 'firstproject-67190.firebaseapp.com',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    measurementId: 'G-ZXBTNP541P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtJOhlm-sSmLNI5dCGJaF6V7sBYJH410',
    appId: '1:364938733915:android:275afc81b8ef9da57f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJHXg3dfjdAi2SNiEUQJm5mi4m1SbfTI',
    appId: '1:364938733915:ios:811fbd8b437543947f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    androidClientId: '364938733915-ch73e8efj5adaf52r09q34kc4gbog70r.apps.googleusercontent.com',
    iosClientId: '364938733915-q8usrcpes75cjm8kk1ihgjrjd3asj0jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.statemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Y3zjqh3wSfUNvx_vjECrdc9Lah2BwUU',
    appId: '1:364938733915:web:3936f4ba777c935b7f127e',
    messagingSenderId: '364938733915',
    projectId: 'firstproject-67190',
    authDomain: 'firstproject-67190.firebaseapp.com',
    databaseURL: 'https://firstproject-67190-default-rtdb.firebaseio.com',
    storageBucket: 'firstproject-67190.firebasestorage.app',
    measurementId: 'G-DFT7QZ0W1T',
  );
}
